Repository SCAI-BIO/kitsune, pull requests merged in 2025-08, with the labels that each got.

#168 refactor(core-model): introduce shared base class for component hierarchy
  client/src/app/app.routes.ts
  client/src/app/core-model-admin/core-model-admin.component.scss
  client/src/app/core-model/base/core-model-base.scss
  client/src/app/core-model/base/core-model-base.ts
  client/src/app/core-model/core-model-admin/core-model-admin.component.html
  client/src/app/core-model/core-model-admin/core-model-admin.component.scss
  client/src/app/core-model/core-model-admin/core-model-admin.component.spec.ts
  client/src/app/core-model/core-model-admin/core-model-admin.component.ts
  client/src/app/core-model/core-model-dialog.service.spec.ts
  client/src/app/core-model/core-model-dialog.service.ts
  client/src/app/core-model/core-model-table.service.spec.ts
  client/src/app/core-model/core-model-table.service.ts
  client/src/app/core-model/core-model.component.ts
  client/src/app/core-model/core-model/core-model.component.html
  client/src/app/core-model/core-model/core-model.component.scss
  client/src/app/core-model/core-model/core-model.component.spec.ts
  client/src/app/core-model/core-model/core-model.component.ts
Labels: frontend

#173 Chore/bump datastew version
  api/app/routers/mappings.py
  api/requirements.txt
Labels: chore

#177 refactor: replace WeaviateClient with PostgresClient across the appli…
  api/app/dependencies.py
  api/app/models.py
  api/app/routers/concepts.py
  api/app/routers/mappings.py
  api/app/routers/models.py
  api/app/routers/terminologies.py
  api/app/routers/visualization.py
  api/app/tasks/import_tasks.py
  postgresql/docker-compose.yml
Labels: python

#178 Chore/bump package versions
  client/package-lock.json
  client/package.json
Labels: chore, javascript

#180 docs: update documentation
  README.md
Labels: documentation

#181 chore: add Open Graph and Twitter Card meta tags for improved social …
  client/src/index.html
Labels: chore

#185 Fix/deployment budget
  client/Dockerfile.dev
  client/Dockerfile.prod
  client/angular.json
Labels: chore

#186 fix: update Keycloak URL to use public Keycloak server
  client/src/environments/environment.production.ts
Labels: bug

#188 Update README.md
  README.md
Labels: chore
